import React, { useState, useEffect } from 'react'
import {
  Volume2, VolumeX, Share2, PhoneCall, ShieldCheck, AlertTriangle,
  FlaskConical, Sparkles, Sprout, CheckCircle2, RotateCcw, Printer, Info, Check
} from 'lucide-react'

export default function DiagnosisResult({ data, onReset }) {
  const [activeTab, setActiveTab] = useState('chemical') // 'chemical' | 'organic' | 'prevention'
  const [isSpeaking, setIsSpeaking] = useState(false)
  const [copied, setCopied] = useState(false)

  const {
    crop, cropHindi, diseaseName, diseaseHindi, pathogen, pathogenHindi,
    severity, severityHindi, confidence, icon, summary, summaryHindi,
    audioText, symptoms, symptomsHindi, organicRemedy, chemicalRemedy, prevention
  } = data

  // Voice narration setup
  useEffect(() => {
    return () => {
      if (typeof window !== 'undefined' && window.speechSynthesis) {
        window.speechSynthesis.cancel()
      }
    }
  }, [])

  const handleSpeakToggle = () => {
    if (typeof window === 'undefined' || !window.speechSynthesis) {
      alert('Speech synthesis is not supported on this browser.')
      return
    }

    if (isSpeaking) {
      window.speechSynthesis.cancel()
      setIsSpeaking(false)
      return
    }

    window.speechSynthesis.cancel()
    const textToSpeak = audioText || `${cropHindi} में ${diseaseHindi} पाया गया है। कृपया संस्तुत उपचार का छिड़काव करें।`
    const utterance = new SpeechSynthesisUtterance(textToSpeak)
    
    // Try to find a Hindi voice if available
    const voices = window.speechSynthesis.getVoices()
    const hindiVoice = voices.find(v => v.lang.includes('hi') || v.lang.includes('Hindi'))
    if (hindiVoice) {
      utterance.voice = hindiVoice
      utterance.lang = 'hi-IN'
    } else {
      utterance.lang = 'hi-IN'
    }
    
    utterance.rate = 0.95
    utterance.pitch = 1.0

    utterance.onend = () => setIsSpeaking(false)
    utterance.onerror = () => setIsSpeaking(false)

    window.speechSynthesis.speak(utterance)
    setIsSpeaking(true)
  }

  // Generate WhatsApp Share Message
  const handleWhatsAppShare = () => {
    const chemicalText = chemicalRemedy?.items
      ?.map(i => `• *${i.name}*: ${i.dose}`)
      .join('\n') || ''

    const msg = encodeURIComponent(
      `🌾 *Kisan Alert - फसल रोग पर्ची (Prescription)* 🌾\n\n` +
      `🌱 *फसल (Crop):* ${crop} (${cropHindi})\n` +
      `🦠 *रोग (Disease):* ${diseaseName} (${diseaseHindi})\n` +
      `⚠️ *गंभीरता:* ${severityHindi}\n\n` +
      `💊 *अनुशंसित दवा और मात्रा (Recommended Dosage):*\n${chemicalText}\n\n` +
      `🌿 *देसी उपाय:* ${organicRemedy?.items?.[0]?.name || 'नीम का तेल'} (${organicRemedy?.items?.[0]?.dose || ''})\n\n` +
      `Generated by Kisan Alert AI Doctor 🚜`
    )
    window.open(`https://api.whatsapp.com/send?text=${msg}`, '_blank')
  }

  const handlePrint = () => {
    if (typeof window !== 'undefined') window.print()
  }

  const severityColor =
    severity === 'Critical'
      ? 'bg-rose-500/20 text-rose-300 border-rose-500/40'
      : severity === 'High'
      ? 'bg-amber-500/20 text-amber-300 border-amber-500/40'
      : 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'

  return (
    <div className="space-y-6 animate-fade-up">
      {/* Hero Prescription Header Card */}
      <div className="relative rounded-3xl p-6 md:p-8 overflow-hidden text-white shadow-2xl bg-gradient-to-br from-slate-900 via-emerald-950 to-brand-950 border border-emerald-500/30">
        <div className="absolute -top-24 -right-24 w-72 h-72 rounded-full bg-brand-500/20 blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-1/3 w-64 h-64 rounded-full bg-emerald-500/10 blur-3xl pointer-events-none" />

        <div className="relative z-10">
          {/* Top badges */}
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <span className="text-3xl">{icon || '🌱'}</span>
              <div>
                <span className="text-xs font-semibold text-emerald-300 uppercase tracking-wider">
                  {crop} · {cropHindi}
                </span>
                <div className="text-xs text-slate-400">{pathogen} ({pathogenHindi})</div>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <span className={`px-3 py-1 rounded-full text-xs font-bold border ${severityColor}`}>
                {severityHindi}
              </span>
              <span className="px-3 py-1 rounded-full bg-emerald-500/20 border border-emerald-400/40 text-emerald-300 text-xs font-bold font-mono">
                {confidence}% AI MATCH
              </span>
            </div>
          </div>

          {/* Disease Title */}
          <div className="mt-5">
            <div className="text-sm font-medium text-emerald-200">पहचाना गया रोग / Detected Diagnosis:</div>
            <h2 className="text-2xl md:text-4xl font-black text-white mt-1">
              {diseaseName}
            </h2>
            <div className="text-lg md:text-xl font-bold text-emerald-400 mt-0.5">
              {diseaseHindi}
            </div>
          </div>

          <p className="mt-4 text-sm text-slate-300 leading-relaxed max-w-3xl">
            {summaryHindi || summary}
          </p>

          {/* Voice Narration Bar ("सुनिए क्या करना है") */}
          <div className="mt-6 p-4 rounded-2xl bg-white/10 backdrop-blur border border-white/20 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <button
                onClick={handleSpeakToggle}
                className={`w-12 h-12 rounded-xl grid place-items-center transition shadow-lg ${
                  isSpeaking
                    ? 'bg-rose-500 text-white animate-pulse'
                    : 'bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold'
                }`}
                title={isSpeaking ? 'Awaaz rokein' : 'Awaaz me sunein'}
              >
                {isSpeaking ? <VolumeX className="w-6 h-6" /> : <Volume2 className="w-6 h-6" />}
              </button>
              <div>
                <div className="text-sm font-bold text-white flex items-center gap-2">
                  <span>Awaaz me sunein (Voice Audio)</span>
                  {isSpeaking && (
                    <span className="flex gap-1 items-end h-3">
                      <span className="w-1 bg-emerald-400 h-2 animate-bounce" />
                      <span className="w-1 bg-emerald-400 h-3 animate-bounce [animation-delay:150ms]" />
                      <span className="w-1 bg-emerald-400 h-1.5 animate-bounce [animation-delay:300ms]" />
                    </span>
                  )}
                </div>
                <div className="text-xs text-emerald-200/80">
                  {isSpeaking ? 'Bol kar samjha raha hai... (Speaking)' : 'Audio dabayein aur poora ilaj Hindi me sunein'}
                </div>
              </div>
            </div>

            {/* Quick share actions inside header */}
            <div className="flex items-center gap-2 w-full sm:w-auto">
              <button
                onClick={handleWhatsAppShare}
                className="flex-1 sm:flex-none inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs shadow-md transition"
              >
                <Share2 className="w-4 h-4" />
                WhatsApp पर्ची
              </button>
              <a
                href="#/call"
                className="flex-1 sm:flex-none inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl bg-white/20 hover:bg-white/30 text-white font-semibold text-xs border border-white/20 transition"
              >
                <PhoneCall className="w-4 h-4 text-emerald-300" />
                Call Krishi Doctor
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* Symptoms checklist */}
      {symptoms && symptoms.length > 0 && (
        <div className="glass rounded-3xl p-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-400 to-amber-600 grid place-items-center text-white shadow-md">
              <AlertTriangle className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-slate-900 text-base">Key Symptoms (रोग के मुख्य लक्षण)</h3>
              <p className="text-xs text-slate-500">पत्तियों पर दिखने वाले प्रमुख लक्षण व पहचान के बिंदु</p>
            </div>
          </div>

          <div className="mt-4 grid sm:grid-cols-2 gap-3">
            {symptoms.map((s, idx) => {
              const hindiText = symptomsHindi?.[idx]
              return (
                <div key={idx} className="flex items-start gap-3 p-3.5 rounded-2xl bg-white/90 border border-slate-100 shadow-sm hover:border-amber-300 transition">
                  <div className="w-6 h-6 rounded-lg bg-amber-100 text-amber-800 font-bold text-xs grid place-items-center shrink-0 mt-0.5">
                    {idx + 1}
                  </div>
                  <div className="space-y-1">
                    {hindiText && (
                      <div className="text-xs font-bold text-slate-900 leading-snug">
                        {hindiText}
                      </div>
                    )}
                    <div className="text-[11px] text-slate-500 font-medium leading-relaxed">
                      {s}
                    </div>
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Treatment Tabs Navigation */}
      <div className="flex flex-wrap gap-2 p-1.5 glass rounded-2xl">
        <button
          onClick={() => setActiveTab('chemical')}
          className={`flex-1 min-w-[140px] flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-xs md:text-sm font-bold transition-all ${
            activeTab === 'chemical'
              ? 'bg-gradient-to-r from-brand-600 to-emerald-600 text-white shadow-lg'
              : 'text-slate-600 hover:text-slate-900 hover:bg-white/60'
          }`}
        >
          <FlaskConical className="w-4 h-4" />
          🧪 रासायनिक उपचार (Chemical)
        </button>
        <button
          onClick={() => setActiveTab('organic')}
          className={`flex-1 min-w-[140px] flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-xs md:text-sm font-bold transition-all ${
            activeTab === 'organic'
              ? 'bg-gradient-to-r from-emerald-600 to-teal-600 text-white shadow-lg'
              : 'text-slate-600 hover:text-slate-900 hover:bg-white/60'
          }`}
        >
          <Sprout className="w-4 h-4" />
          🌿 जैविक व देसी नुस्खा (Organic)
        </button>
        <button
          onClick={() => setActiveTab('prevention')}
          className={`flex-1 min-w-[140px] flex items-center justify-center gap-2 py-3 px-4 rounded-xl text-xs md:text-sm font-bold transition-all ${
            activeTab === 'prevention'
              ? 'bg-gradient-to-r from-cyan-600 to-blue-600 text-white shadow-lg'
              : 'text-slate-600 hover:text-slate-900 hover:bg-white/60'
          }`}
        >
          <ShieldCheck className="w-4 h-4" />
          🛡️ बचाव व रोकथाम (Prevention)
        </button>
      </div>

      {/* Tab 1: Chemical Treatment */}
      {activeTab === 'chemical' && (
        <div className="glass rounded-3xl p-6 md:p-7 space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h4 className="font-bold text-slate-900 text-base">{chemicalRemedy?.title}</h4>
              <p className="text-xs text-slate-500">Go to local Krishi Seva Kendra with these exact salts and dosages</p>
            </div>
            <span className="text-[10px] px-2.5 py-1 rounded-full bg-amber-100 text-amber-800 font-bold">
              Follow Precautions
            </span>
          </div>

          <div className="space-y-3 mt-4">
            {chemicalRemedy?.items?.map((item, idx) => (
              <div key={idx} className="p-4 rounded-2xl bg-white border border-slate-100 shadow-sm hover:border-brand-300 transition">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="font-bold text-slate-900 text-sm flex items-center gap-2">
                    <span className="w-6 h-6 rounded-lg bg-emerald-100 text-emerald-800 text-xs font-black grid place-items-center">
                      {idx + 1}
                    </span>
                    <span>{item.name}</span>
                  </div>
                  <div className="inline-block px-3 py-1 rounded-lg bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold font-mono">
                    मात्रा (Dosage): {item.dose}
                  </div>
                </div>
                {item.timing && (
                  <div className="mt-2 text-xs text-slate-600 pl-8 flex items-center gap-1.5">
                    <Info className="w-3.5 h-3.5 text-slate-400" />
                    <span><strong>स्प्रे समय (Timing):</strong> {item.timing}</span>
                  </div>
                )}
              </div>
            ))}
          </div>

          <div className="mt-4 p-3.5 rounded-2xl bg-amber-50 border border-amber-200 text-xs text-amber-900 flex items-start gap-2.5">
            <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <strong>सावधानी (Pesticide Safety):</strong> तेज धूप या दोपहर में छिड़काव न करें। सुबह 8 से 11 बजे या शाम को 4 बजे के बाद छिड़काव करें। मास्क और दस्ताने अवश्य पहनें।
            </div>
          </div>
        </div>
      )}

      {/* Tab 2: Organic Remedies */}
      {activeTab === 'organic' && (
        <div className="glass rounded-3xl p-6 md:p-7 space-y-4">
          <div>
            <h4 className="font-bold text-slate-900 text-base">{organicRemedy?.title}</h4>
            <p className="text-xs text-slate-500">Low-cost, zero-chemical natural treatments made from farm ingredients</p>
          </div>

          <div className="space-y-3 mt-4">
            {organicRemedy?.items?.map((item, idx) => (
              <div key={idx} className="p-4 rounded-2xl bg-white border border-slate-100 shadow-sm hover:border-emerald-300 transition">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                  <div className="font-bold text-slate-900 text-sm flex items-center gap-2">
                    <span className="w-6 h-6 rounded-lg bg-teal-100 text-teal-800 text-xs font-black grid place-items-center">
                      🌿
                    </span>
                    <span>{item.name}</span>
                  </div>
                  <div className="inline-block px-3 py-1 rounded-lg bg-teal-50 border border-teal-200 text-teal-800 text-xs font-bold">
                    अनुपात: {item.dose}
                  </div>
                </div>
                <p className="mt-2 text-xs text-slate-600 pl-8 leading-relaxed">
                  {item.desc}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab 3: Prevention Checklist */}
      {activeTab === 'prevention' && (
        <div className="glass rounded-3xl p-6 md:p-7 space-y-4">
          <div>
            <h4 className="font-bold text-slate-900 text-base">भविष्य में रोकथाम और बचाव (Prevention Guidelines)</h4>
            <p className="text-xs text-slate-500">Follow these farm practices to stop the disease from recurring next season</p>
          </div>

          <ul className="space-y-2.5 mt-4">
            {prevention?.map((tip, idx) => (
              <li key={idx} className="flex items-start gap-3 p-3.5 rounded-2xl bg-white border border-slate-100 text-xs text-slate-700 leading-relaxed">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Action footer */}
      <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
        <button
          onClick={onReset}
          className="inline-flex items-center gap-2 px-5 py-3 rounded-2xl glass hover:bg-white text-slate-700 font-bold text-sm shadow-sm transition"
        >
          <RotateCcw className="w-4 h-4 text-brand-600" />
          Scan Another Leaf (नया फोटो जांचें)
        </button>

        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-2 px-4 py-3 rounded-2xl glass hover:bg-white text-slate-700 font-semibold text-sm shadow-sm transition"
          >
            <Printer className="w-4 h-4 text-slate-500" />
            Print पर्ची
          </button>
          <button
            onClick={handleWhatsAppShare}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-sm shadow-xl shadow-emerald-600/30 transition"
          >
            <Share2 className="w-4 h-4" />
            दुकानदार को WhatsApp भेजें
          </button>
        </div>
      </div>
    </div>
  )
}
